"""empty message

Revision ID: 39a2f06d4e69
Revises: None
Create Date: 2014-10-20 20:59:14.612525

"""

# revision identifiers, used by Alembic.
revision = '39a2f06d4e69'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #contains a line which adds the foreign key to the posts table
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #contains a line which removes the foreign key from the posts table
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###
